### ISSUE TITLE
Error: subprocess.CalledProcessError: Command '['build/query_devices']' died with <Signals.SIGSEGV: 11>.

### ISSUE THREAD

**Issue by fubowen1229** [NVlabs/PoseRBPF#5]
## Error
When running `python ycb_renderer.py`, the following error occurs. Though I can built `CppYCBRenderer` successfully, there seems to be some mistakes in it. 
```
Traceback (most recent call last):
  File "ycb_renderer.py", line 702, in <module>
    renderer = YCBRenderer(w, h, render_marker=False)
  File "ycb_renderer.py", line 80, in __init__
    self.r = CppYCBRenderer.CppYCBRenderer(width, height, get_available_devices()[gpu_id])
  File "/data2/fbw/PoseRBPF/ycb_render/get_available_devices.py", line 7, in get_available_devices
    num_devices = int(subprocess.check_output(["{}/query_devices".format(executable_path)]))
  File "/home/fbw/anaconda3/envs/pose_rbpf_env/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/fbw/anaconda3/envs/pose_rbpf_env/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/data2/fbw/PoseRBPF/ycb_render/build/query_devices']' died with <Signals.SIGSEGV: 11>.
```
When running `get_available_devices.py`, a similar error occurs. 
```
Traceback (most recent call last):
  File "get_available_devices.py", line 26, in <module>
    print(get_available_devices())
  File "get_available_devices.py", line 7, in get_available_devices
    num_devices = int(subprocess.check_output(["{}/query_devices".format(executable_path)]))
  File "/home/fbw/anaconda3/envs/pose_rbpf_env/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/home/fbw/anaconda3/envs/pose_rbpf_env/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['build/query_devices']' died with <Signals.SIGSEGV: 11>.
```
It seems there is something wrong in cmake. 

## Environment
Ubuntu 16.04
python 3.6
cuda 10.0
cmake 3.5.1

**Comment by lizolson1** [comment]
Were you able to fix this?

**Comment by fubowen1229** [comment]
> Were you able to fix this?

No. However, I tried on another server with `gcc 5.4.0` & `cmake 3.18.4`, and this problem didn't emerge.

**Comment by hajungong007** [comment]
> Were you able to fix this?

 self.r = CppYCBRenderer.CppYCBRenderer(width, height, 0)
